// ----------------------------------------------
// functions from the Graphene library
// ----------------------------------------------

fn MOD(m : integer, n : integer) -> integer
   m - n*(m/n)

// ----------------------------------------------
// function to reverse a number
// ----------------------------------------------

fn reverse(n : integer) -> integer
   reverseL(n, 0)

fn reverseL(n : integer, nR : integer) -> integer
   if (n == 0)
      nR
   else
      reverseL(n / 10, 10 * nR + MOD(n, 10))

// ----------------------------------------------
// determine if a number is a palindrome
// ----------------------------------------------

fn isPalindrome(n : integer) -> boolean
   0 == (n - reverse(n))

// ----------------------------------------------
// main function: takes command-line argument
// ----------------------------------------------

fn main(number : integer) -> boolean
   print(number)
   print(reverse(number))
   isPalindrome(number)
